# 排序节点的组织定义
OrdererOrgs:
  - Name: ZJU1 # 名称
    Domain: zjuwlan1.com # 域名
    Specs: # 节点域名：orderer.zjuwlan1.com
      - Hostname: orderer # 主机名

# peer节点的组织定义
PeerOrgs:
  # ZJU2-组织
  - Name: ZJU2 # 名称
    Domain: zjuwlan2.com # 域名
    Template: # 使用模板定义。Count 指的是该组织下组织节点的个数
      Count: 2 # 节点域名：peer0.zjuwlan2.com 和 peer1.zjuwlan2.com
    Users: # 组织的用户信息。Count 指该组织中除了 Admin 之外的用户的个数
      Count: 1 # 用户：Admin 和 User1

  # JD-组织
  - Name: ZJU3
    Domain: zjuwlan3.com
    Template:
      Count: 2 # 节点域名：peer0.zjuwlan3.com 和 peer1.zjuwlan3.com
    Users:
      Count: 1 # 用户：Admin 和 User1
